### ISSUE TITLE
Unable to install pip packages from source

### ISSUE THREAD

**Issue by InigoMoreno** [ros-infrastructure/rosdep#1006]
I am trying to add a pip package from source to a custom rosdep.yaml:
```yaml
rtde-pip:
  ubuntu:
    pip:
      packages: [UrRtde @ git+https://github.com/UniversalRobots/RTDE_Python_Client_Library@b23ae7a5d2e5046c1a87e2edfd4f4da5262852e8]
```

This installs the package successfully but "Failed to detect successful installation of [UrRtde @ git+https://github.com/UniversalRobots/RTDE_Python_Client_Library@b23ae7a5d2e5046c1a87e2edfd4f4da5262852e8]"
