### ISSUE TITLE
Cannot build cartographer due to rosdep lacking definitions

### ISSUE THREAD

**Issue by Ocoras** [ros-infrastructure/rosdep#741]
I am attempting to build cartographer on ROS 2 Dashing on Arch Linux. There have been multiple insufficient definitions for rosdep which I have been fixing on [my personal fork](https://github.com/Ocoras/rosdistro) (which I will later hope to pull request) however my build continues to fail with the below error:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cartographer_ros: No definition of [urdfdom_headers] for OS [arch]
```
`urdfdom_headers` is defined in [https://raw.githubusercontent.com/ros/rosdistro/master/dashing/distribution.yaml](https://raw.githubusercontent.com/ros/rosdistro/master/dashing/distribution.yaml) (found using `rosdep where-defined`) to be:
```yaml
  urdfdom_headers:
    doc:
      type: git
      url: https://github.com/ros/urdfdom_headers.git
      version: dashing
    release:
      tags:
        release: release/dashing/{package}/{version}
      url: https://github.com/ros2-gbp/urdfdom_headers-release.git
      version: 1.0.4-1
    source:
      type: git
      url: https://github.com/ros/urdfdom_headers.git
      version: dashing
    status: developed
```
Thus I cannot find a simple solution to link for Arch Linux, since it is my understanding that this package should be built from the git source.
