### ISSUE TITLE
Rosdep typo in custom yaml can permanently corrupted depedency name 

### ISSUE THREAD

**Issue by fprott** [ros-infrastructure/rosdep#927]
I found an interesting and pretty serious bug under ROS1 Noetic (Ubuntu 20.04.6 LTS, Python 3.8.10).

Basically I manged to permanently corrupt the name of a dependency.

I wanted to build myself a yaml file to handle a lot of dependencies in a structured manner. Most of my dependencies where apt-get related, however one was pip related. I forgot that so my file looked like that.

```
python-shapely:
  ubuntu:
    packages: [shapely]
```

I run the file and noticed the error right away. So I stopped rosdep while it was running and corrected my mistake. 
```
python-shapely:
  ubuntu:
    pip:
      packages: [shapely]
```

No big deal, right? Nope! No matter what I do or what I do the dependency python-shapely will only and always trigger the apt-get install command as well as the following error
```
executing command [sudo -H apt-get install -y python-shapely]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-shapely
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y python-shapely] failed
  apt: Failed to detect successful installation of [python-shapely]
```
Basically the name has become toxic. If I use any other name the system works as intended! So if you try:
```
python-shapely: #breaks everything
  ubuntu:
    pip:
      packages: [shapely]
      
python-example: #works like a charm
  ubuntu:
    pip:
      packages: [shapely]
```

I tried to delete the cache in .ros/rosdep/ by deleting the folder. I tried to reinstall the rosdep tool. Heck, I even restated my machine for the first time in forever. I even searched trough every file mentioning python-shapely, but the freaking thing is saved no where. I tried everything, the name is just broken.  

So, any way to fix this? Where the heck is the cache responsible for that?
